name: Build and Release Marp Presentation

on:
  push:
    branches:
      - main  # 你可以修改为你的默认分支

    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build Marp Presentation
        run: npx marp ./main.md --output build.pdf

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: marp-presentation
          path: build.pdf

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: marp-presentation

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
